-- AlterTable
ALTER TABLE "RegisterTokens" ALTER COLUMN "invalid" DROP NOT NULL,
ALTER COLUMN "invalid" SET DEFAULT false,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
